version: '3'

volumes:
  caddy_data:
  caddy_config:

services:
  api:
    image: hearts:0.3
    restart: always
  client:
    image: hearts-client:latest
    environment: 
      - SITE_ADDRESS=localhost:80
      - API_ADDRESS=api:8080
    depends_on:
      - api
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    ports:
      - 80:80
      - 443:443